@startuml

'left to right direction

title Domain Model - US021

skinparam classAttributeIconSize 0

hide circle
hide methods


class Entry {
    Description
    Degree of urgency
    Approximate expected duration
}

class ToDoList {
    Tasks
}

Entry "0..*" - "1" ToDoList: is in >

@enduml