@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":RegisterSkillsGUI" as RSUI
participant ":RegisterSkillsController" as RSC
participant ":Repository" as R
participant ":CollaboratorRepository" as RR
participant ":SkillRepository" as TCR

activate HRM
HRM -> RSUI: asks to register a new skill that a collaborator may have
activate RSUI
    RSUI -> RSC: get all skill categories
    activate RSC
        RSC -> R: get Instance()
        activate R
        RSC <-- R: repositories
        deactivate R
        RSC -> RR: getCollaboratorRepository()
        activate RR
        RSC <-- RR: CollaboratorRepository
        deactivate RR
        RSC -> TCR: getSkill()
        activate TCR
        RSC <-- TCR: getSkill
        deactivate TCR
    RSUI <-- RSC: registered skill categories
    deactivate RSC
HRM <-- RSUI : shows the list of skills to register
deactivate RSUI
HRM -> RSUI: selects a collaborator
activate RSUI
RSUI --> HRM: requests skill(s) to be registered

loop while HRM enters y
deactivate RSUI
HRM -> RSUI: selects a skill category
activate RSUI
HRM <-- RSUI: asks if there are more skill(s) to be registered
deactivate RSUI
HRM -> RSUI: enter x to stop or y to continue registered skills
activate RSUI
end
    RSUI -> RSC: registerSkill(collaborator, skillList)
    activate RSC
        RSC -> TCR  : registerSkill(collaborator, skillList)
        activate TCR
            TCR -> TCR  : registerSkill(collaborator, skillList)
            RSC <-- TCR : operation success
        deactivate TCR
        RSUI <-- RSC: operation success
    deactivate RSC
HRM <-- RSUI: displays operation success
deactivate RSUI
deactivate HRM
@enduml