@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Fleet Manager (FM)" as FM
participant ":System" as System
autonumber

title System Sequence Diagram (SSD) - Alternative One
activate FM

FM -> System : Requests to register a vehicle
activate System
alt Valid request
System -> System: Validates request
    System -> System: Displays vehicle registration form
    System -> FM : Requests vehicle data (model, brand, type, tare,gross weight, current Km, register date, acquisition date, maintenance/check up frequency, vehicle plate)
else Invalid request
    System --> FM: Notifies invalid request
end
deactivate System
    FM -> System : Types requested data
    activate System
alt Valid data
System -> System: Validates vehicle details
    System -> System: Saves vehicle information
    System -> FM : Shows all data and requests confirmation
else Invalid data
System --> FM: Notifies invalid vehicle details
end
deactivate System
    FM -> System : Confirms data
    activate System

    System -> FM: Notifies successful vehicle registration
deactivate System

@enduml