@startuml
'https://plantuml.com/sequence-diagram
actor "Quality Assessment Team Manager" as QAM
autonumber

QAM -> System: Authentication Request
activate System
System --> QAM: Authentication Response
deactivate System
alt Valid Request
    alt QAM run tests for inputs of variable size
        QAM -> System: Requests test
            activate System
            System --> QAM: Asks for input of variable size
            deactivate System
        loop while  QAM provides input of variable size
            QAM -> System: Provides input of variable size
            activate System
            System --> QAM: Confirms input of variable size
            deactivate System
        else QAM does not provide input of variable size
            QAM -> System: Does not provide input of variable size
            activate System
            System --> QAM: Rejects input of variable size
            deactivate System
        end
    end
    else Invalid Request
        System --> QAM: Returns Invalid Request
        activate System
        System --> QAM: Asks for new Authentication Request
        deactivate System
end
@enduml