@startuml
actor "Human Resources Manager" as HRM
participant "System" as System
autonumber
HRM -> System: Request to register skill(s)
activate System
loop while HRM enters skill(s) details
alt Valid request
    System -> System: Display skill(s) registration form
    System --> HRM: Provide skill(s) details
else Invalid request
    System --> HRM: Notify invalid request
    deactivate System
end

HRM -> System: Provide skill(s) details
activate System
alt Valid skill(s) details
System -> System: Validate skill(s) details
    System -> System: Save skill(s) information
    System --> HRM: Notify successful skill(s) registration
else Invalid skill(s) details
    System --> HRM: Notify invalid skill(s) details
    deactivate System
end
end

deactivate System
@enduml
