@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a skill to a collaborator
    activate System


    System --> Employee : requests data (i.e. name or id of the collaborator, and skill)
    deactivate System

    Employee -> System : types requested data
    activate System


    System --> Employee : shows the collaborator chosen and the skill to add
    deactivate System

    Employee -> System : confirms the data
    activate System

    System --> Employee : shows the success of the operation
    deactivate System

@enduml
