@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a skill to a collaborator
    activate System


    System --> Employee : requests the collaborator to add the skill
    deactivate System

    Employee -> System : types requested data
    activate System

    System --> Employee : Shows the available skills and asks which ones to add
    deactivate System

    Employee -> System : chooses the skill(s) to add
    activate System

    System --> Employee : shows the collaborator chosen and the skill to add
    deactivate System

    Employee -> System : confirms the data
    activate System

    System --> Employee : shows the success of the operation
    deactivate System

@enduml
