@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a skill to a collaborator
    activate System

        System --> Employee : requests data (i.e. name or id of the collaborator, and skill)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : Updates the collaborator with the skill and displays all the skills of the collaborator
    deactivate System



@enduml