@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":VehicleController" as CTRL
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository

autonumber 12
-> CTRL : createMaintenanceList(vehiclesList)

autonumber 12.1

activate CTRL
    group Create Maintenance List

                        CTRL -> VehicleRepository : getMaintenanceRepository()
                        activate VehicleRepository

                            VehicleRepository --> CTRL: MaintenanceRepository
                        deactivate VehicleRepository

                        CTRL -> VehicleRepository : createMaintenanceList(vehiclesList)
                        activate VehicleRepository

                        VehicleRepository --> CTRL : maintenanceList
                        deactivate VehicleRepository

                    deactivate CTRL
    end group

    autonumber 13
    <-- CTRL : taskCategory

deactivate CTRL

@enduml