@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Vehicle and Equipment Fleet Manager (VFM)" as VFM
participant ":ListMaintenanceUI" as UI
participant ":VehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository


activate VFM

    VFM -> UI :list vehicles needing maintenance
    activate UI



        UI -> CTRL : getVehiclesList()
        activate CTRL

            CTRL -> VehicleRepository : getVehiclesList()
            activate VehicleRepository

                VehicleRepository --> CTRL : vehicleList
            deactivate VehicleRepository

            CTRL --> UI : vehicleList
        deactivate CTRL


        UI -> CTRL : generateMaintenanceList(vehiclesList)
        activate CTRL

            CTRL -> CTRL : createMaintenanceList(vehiclesList)
            activate CTRL

            CTRL --> UI : maintenanceList
        deactivate CTRL

        UI --> VFM : shows list
    deactivate UI

deactivate VFM

@enduml