@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox
actor "Vehicle and Equipment Fleet Manager (VFM)" as VFM
participant ":ListMaintenanceUI" as UI
participant ":ListMaintenanceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant "maintenanceRepository:\nMaintenanceRepository" as MaintenanceRepository
participant "maintenanceList\n:MaintenanceList" as MaintenanceList
activate VFM

    VFM -> UI : requests to list vehicles needing maintenance
    activate UI

        UI -> CTRL** : create

        UI -> CTRL : getVehiclesList()
        activate CTRL

            CTRL --> UI : vehicleList
        deactivate CTRL

        UI --> UI : keep vehicleList

        UI -> CTRL : createMaintenanceList(vehiclesList)
        activate CTRL

        CTRL -> MaintenanceRepository: createMaintenanceList(vehicleList)
        activate MaintenanceRepository


        MaintenanceRepository --> CTRL: maintenanceList
        deactivate MaintenanceRepository

        CTRL --> CTRL : maintenanceList


            CTRL --> UI : maintenanceList
        deactivate CTRL

        UI --> VFM : shows maintenance List
    deactivate UI

deactivate VFM

@enduml