@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox
actor "Vehicle and Equipment Fleet Manager (VFM)" as VFM
participant ":ListMaintenanceUI" as UI
participant ":VehicleController" as CTRL
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
activate VFM

    VFM -> UI : requests to list vehicles needing maintenance
    activate UI

        UI -> CTRL : getVehiclesList()
        activate CTRL

            ref over CTRL
                Get Vehicle List
            end ref

            CTRL --> UI : vehicleList
        deactivate CTRL

        UI --> UI : keep vehicleList

        UI -> CTRL : generateMaintenanceList(vehiclesList)
        activate CTRL

        CTRL -> VehicleRepository: createMaintenanceList(vehicleList)
        activate VehicleRepository

            ref over VehicleRepository
                Create Maintenance List
            end ref

        VehicleRepository --> CTRL: maintenanceList
        deactivate VehicleRepository

            CTRL --> UI : maintenanceList
        deactivate CTRL

        UI --> VFM : shows maintenance List
    deactivate UI

deactivate VFM

@enduml