@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":VehicleController" as CTRL

autonumber 3

 -> CTRL : getVehiclesList()
autonumber 3.1
activate CTRL
    group Get Vehicle List

            CTRL ->VehicleRepository : getVehicleRepository()
            activate VehicleRepository

            VehicleRepository --> CTRL: VehicleRepository
            deactivate VehicleRepository

            CTRL -> VehicleRepository : getVehiclesList()
            activate VehicleRepository

            VehicleRepository --> CTRL : vehiclesList
            deactivate VehicleRepository

    end

    autonumber 4
    <-- CTRL  : vehicleList
deactivate CTRL


@enduml