@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "organization\n:Organization" as ORG
participant "skill\n:Skill" as SKILL

autonumber 16
-> ORG: addSkillsToCollaborator(Skills, employee)

autonumber 16.1
activate ORG
    group add Skills to Collaborator

        ORG -> SKILL**: addSkillToEmployee (skills, employee)



        loop for each skill in Skills
            SKILL -> employee: addSkill (skill, employee)
        end
    end

    autonumber 17
    <-- ORG : task
deactivate ORG


@enduml