@startuml
actor "Human Resources Manager (HRM)" as HRM

participant "System" as System

HRM -> System: Request to register job
activate System
loop while HRM provides job details
alt Valid request
    System -> System: Validate request
    System -> System: Display job registration form
    System -> HRM: Provide job details
else Invalid request
    System --> HRM: Notify invalid request
end

HRM -> System: Provide job details
alt Valid job details
    System -> System: Validate job details
    System -> System: Save job information
    System --> HRM: Notify successful job registration
else Invalid job details
    System --> HRM: Notify invalid job details
end
end

deactivate System
@enduml
