@startuml

'left to right direction

title Domain Model

hide methods
hide circle

class Entry {
    requiredTask
    urgency
    expectedDuration
}

class ToDoList{
    entries
}

class Agenda{
    entries
}



ToDoList "1" -  "*" Entry: Contains  >
Entry "*" - "1" Agenda: gets added to >

@enduml