@startuml

'left to right direction

title Domain Model

hide methods
hide circle

class Entry {
    requiredTask
    urgency
    expectedDuration
}

class ToDoList{
    entries
}

class Agenda{
    AgendaEntries
}

class AgendaEntry{
    entry
    startDate
    endDate
    duration
    Team
    vehicles
}


ToDoList "1" -  "*" Entry: Contains  >
Entry "*" - "1" AgendaEntry: used to create >
AgendaEntry "1" - "1" Agenda: gets added to >
@enduml