@startuml

'left to right direction

title Domain Model

hide methods
hide circle



class Collaborator {
    name
    birthdate
    admission date
    address
    contact
    identification document
    identification number
}

class TechnicalSkill {
        name
        shortDescription
        fullDescription
}

TechnicalSkill "0...*" - "*" Collaborator : is assigned to >

@enduml