@startuml
!theme plain

'left to right direction

hide methods
hide circle

class company{
     name
     address
     contactInfo

}

class Collaborator {
     name
     birthdate
     admissionDate
     address
     TaxpayerNumber
     contactInfo
     idDocType
     idDocNumber
}

class Skill {
    name
}

class HRM {
    name
    birthdate
    admissionDate
    address
    Taxpayer number
    contactInfo
    idDocType
    idDocNumber
}

company "1" - "*" HRM : has 1...* >
company "1" -- "*" Collaborator : has >
HRM "1" -- "*" Skill : registers >
HRM "1" - "*" Collaborator : registers >
Skill "0...*" -left "*" Collaborator : is assigned to >

@enduml