@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterGreenSpaceUI {
}

class GreenSpaceController {
    + getGreenSpace(name, address)
    + getGreenSpaceType()
    + saveNewGreenSpace(name, address, area, type)
    +  storeGreenSpace(greenSpace)
}



class GreenSpaceRepository {
    + getGreenSpace(name, address)
    + getGreenSpaceType()
    + storeGreenSpace(greenSpace)
}
class GreenSpace {
    - String name
    - Type type
    - Double area

   + saveNewGreenSpace(name, address, area, type)
}
class Repositories {
    + getInstance()
    + getGreenSpaceRepository()
}
class Address {
    - String street
    - String city
    - String zipCode

    + createAddress(street, city, zipCode)
    }
RegisterGreenSpaceUI ..> GreenSpaceController
GreenSpaceController ..> GreenSpaceRepository
GreenSpaceController .> Repositories
Repositories .> GreenSpaceRepository
GreenSpaceRepository --> "*"GreenSpace
GreenSpace"1" --> "1"Address

@enduml