@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 3

participant ":VehicleController" as CTRL
participant "vehicleRepository:\nVehicleRepository" as VehicleRepository


        -> CTRL : getVehiclesList()
        activate CTRL
            group Get Vehicle List

            CTRL -> VehicleRepository : getVehicleRepository()
            activate VehicleRepository

                VehicleRepository --> CTRL: VehicleRepository
            deactivate VehicleRepository

            CTRL -> VehicleRepository : getVehiclesList()
            activate VehicleRepository

                VehicleRepository --> CTRL : vehicleList
            deactivate VehicleRepository

            end
             <-- CTRL : vehicleList
            deactivate CTRL

@enduml