
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as ADM
participant ":AddToDoTaskUI" as UI
participant ":AddToDoTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant ":repositories\n:Repositories" as PLAT

participant ":DegreeOfUrgencyRepository" as DOUR
participant ":ToDoListRepository" as TDR
participant "task\n:Task" as TASK

activate ADM

    ADM -> UI : asks to add a new entry to the To-Do List
    activate UI

        UI -> CTRL : getDegreeOfUrgencyList()
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getDegreeOfUrgencyRepository()
            activate PLAT

                PLAT --> CTRL : degreeOfUrgencyRepository
            deactivate PLAT

            CTRL -> DOUR : getDegreeOfUrgencyList()
            activate DOUR

                DOUR --> CTRL : degreeOfUrgencyList
            deactivate DOUR

            CTRL --> UI : degreeOfUrgencyList
        deactivate CTRL

        UI --> ADM : shows a list of degrees of urgency and asks to select one (degreeOfUrgencyList)
    deactivate UI

    ADM -> UI : selects a degree of urgency
    activate UI

        UI --> ADM : requests data (taskDescription, taskDuration)
    deactivate UI

    ADM -> UI : types data
    activate UI

        UI --> ADM : shows all data and requests confirmation (taskDescription, taskDuration, degreeOfUrgency)
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : addTask(taskDescription, taskDuration, degreeOfUrgency)
        activate CTRL

            CTRL -> PLAT : getToDoListRepository()
            activate PLAT

                PLAT --> CTRL : toDoListRepository
            deactivate PLAT

            CTRL -> TDR : addTask(taskDescription, taskDuration, degreeOfUrgency)
            activate TDR

                TDR -> TASK** : createTask(taskDescription, taskDuration, degreeOfUrgency)
                TDR --> TDR : validateEntry(entry)
                TDR --> TDR : saveEntry(entry)
                TDR --> CTRL : boolean
            deactivate TDR

            CTRL --> UI : boolean
        deactivate CTRL

        UI --> ADM : displays operation success
    deactivate UI

deactivate ADM

@enduml