@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Green Space Manager" as GSM
participant ":PostponeEntryUI" as UI
participant ":AgendaController" as AgendaCTRL
participant "AgendaRepository:\nAgendaRepository" as AgendaRepository
participant "Database:\nDatabase" as Database

activate GSM
    GSM -> UI : initiatePostponeEntry(entryId, newDate)
    activate UI
    UI -> AgendaCTRL: fetchEntryDetails(entryId)
    activate AgendaCTRL

        AgendaCTRL -> AgendaRepository : getEntryDetails(entryId)
        activate AgendaRepository

            AgendaRepository -> Database : queryEntryDetails(entryId)
            activate Database

                Database -> AgendaRepository : return entryDetails
            deactivate Database

            AgendaRepository -> AgendaCTRL: return entryDetails
        deactivate AgendaRepository

        AgendaCTRL -> UI: return entryDetails
    deactivate AgendaCTRL

    UI -> GSM: display entryDetails
    GSM -> UI: submit newDate
    activate UI
        UI -> AgendaCTRL: updateEntryDate(entryId, newDate)
        activate AgendaCTRL

            AgendaCTRL -> AgendaRepository: updateEntryDate(entryId, newDate)
            activate AgendaRepository

                AgendaRepository -> Database: updateEntry(entryId, newDate)
                activate Database

                    Database -> AgendaRepository: confirmUpdate
                deactivate Database

                AgendaRepository -> AgendaCTRL: confirmUpdate
            deactivate AgendaRepository

            AgendaCTRL -> UI: confirmUpdate
        deactivate AgendaCTRL

        UI -> GSM: display confirmation
    deactivate UI
deactivate GSM

@enduml
