@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model US007

class VehicleCheckup {
    IdVehicle
    Date
    CurrentKms
}

VehicleCheckup : registers >
@enduml