@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":AddSkillUI" as UI
participant ":AddSkillController" as CTRL
participant "organization\n:Organization" as ORG

activate ADM

    ADM -> UI : asks to add one or more skills to a collaborator

    activate UI

        UI -> CTRL** : add
        UI -> CTRL : getSkills()
        ref over CTRL
            Get Skills List

        end ref

        activate CTRL

            CTRL --> UI : SkillList
        deactivate CTRL

        UI --> ADM : shows skill list and asks to select one or more
    deactivate UI

    ADM -> UI : selects the desired skills
    activate UI

        UI --> CTRL : requests existing collaborators

        activate CTRL

            CTRL --> UI : returns collaborator list
        deactivate CTRL

    deactivate UI




        UI --> ADM : shows collaborator list and asks to select one to add the desired skills
    deactivate UI

    ADM -> UI : selects the desired collaborator
    activate UI

        UI -> CTRL : addSkill(skills, collaborator)
        activate CTRL

            CTRL -> ORG : addSkill(skills, collaborator)

            activate ORG

                ORG -> ORG : addSkill(skills, collaborator)
                ORG --> CTRL : operation success
            deactivate ORG
            CTRL --> UI : operation success
            deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml