@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Organization Employee" as ADM
participant ":AddSkillUI" as UI
participant ":AddSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "SkillRepository:\nSkillRepository" as SkillRepository
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSAO
participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant "organization\n:Organization" as ORG


activate ADM

        ADM -> UI : asks to add a skill to a collaborator

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getSkillList()
            activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillRepository()
                activate PLAT

                    PLAT --> CTRL: SkillRepository
                deactivate PLAT

                CTRL -> SkillRepository : getSkills()
                activate SkillRepository

                    SkillRepository --> CTRL : SkillList
                deactivate SkillRepository
                CTRL --> UI : SkillList
            deactivate CTRL

        loop while user wants to add skills
            UI --> ADM : shows task category list\n and asks to select one
            ADM -> UI : selects a task category
        end loop




    activate UI

        UI --> ADM : requests collaborator's email
    deactivate UI

    ADM -> UI : types requested email
    activate UI

        UI --> ADM : shows selected skills and collaborator\nand asks for confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL : addSkillToCollaborator(email, skills)
        activate CTRL

            CTRL -> CTRL : getEmployeeFromSession()

                CTRL -> _APP: getInstance()
                activate _APP
                    _APP -> CTRL: appSession
                deactivate _APP


                CTRL -> APP: getCurrentSession()
                activate APP

                    APP --> CTRL: currentSession
                deactivate APP

                CTRL -> SESSAO: email = getUserEmail()
                activate SESSAO

                    SESSAO --> CTRL: email
                deactivate SESSAO


                CTRL -> PLAT: getOrganizationRepository(email)
                activate PLAT

                    PLAT --> CTRL: organizationRepository
                deactivate PLAT


                CTRL -> OrganizationRepository: getOrganizationByEmployeeEmail(email)
                activate OrganizationRepository

                    loop [for each organization
                        OrganizationRepository -> ORG : anyEmployeeHasEmail(email)
                        activate ORG

                             ORG --> OrganizationRepository : true/false
                        deactivate ORG
                    end
                    OrganizationRepository --> CTRL : organization
                deactivate OrganizationRepository

                CTRL -> ORG: getEmployeeByEmail(email)
                activate ORG

                    ORG --> CTRL : employee
                deactivate ORG

                CTRL --> CTRL : employee

            |||
            CTRL -> ORG: addSkill(employee, skills)
            activate ORG

                ORG -> SKILL: addSkillsToCollaborator(skills, collaborator)

                activate SKILL
                    activate employee
                    loop for each skill in Skills
                        SKILL -> employee: addSkill(skill, employee)
                    end

                    employee --> SKILL: updated skill list
                    deactivate employee

                SKILL -> ORG: updated skill list
                deactivate SKILL

                ORG -> CTRL: updated skill list

            deactivate CTRL



        deactivate employee
        deactivate SKILL

            deactivate ORG

            CTRL --> UI: updated skill list
            deactivate CTRL
            UI --> ADM: displays operation success and updated skill list
    deactivate UI

deactivate ADM

@enduml