@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skill {
    - String name
    - String shortDescription
    - String Description

    + Skill(name, shortDescription, Description)
}

class SkillController {
    + getSkillList()
    + registerSkill(skill)
    + updateSkill(skill, name, shortDescription, Description)
    + removeSkill(skill)
}

class Collaborator {
    - String email
    - String name
    - String address
    - String phone
    - Job job
    - List<Skill> skills
    - Date birthDate
    - Date admissionDate
    - String IDtype
    - int taxpayerNumber
    - int citizenNumber
    - boolean isFree

    + Collaborator(email, name, address, phone, job, birthDate, admissionDate, IDtype, taxpayerNumber, citizenNumber, skills)
    + addSkill(skill)
    + removeSkill(skill)
}

class CollaboratorController {
    + checkForDuplicateCollaborator(collaborator)
    + registerCollaborator(name, email, address, phone, job, skills, birthDate, admissionDate, IDtype, taxpayerNumber, citizenNumber)
    + updateCollaborator(collaborator, name, email, address, phone, job, skills, birthDate, admissionDate, IDtype, taxpayerNumber, citizenNumber)
    + removeCollaborator(collaborator)
    + addSkillToACollaborator(skill, collaborator)
    + removeSkillFromACollaborator(skill, collaborator)
}

class AddSkillToCollaboratorUI {
}

class SkillRepository {
    + add(skill)
    + remove(skill)
    + update(skill, name, shortDescription, Description)
    + getSkills()
}

class CollaboratorRepository {
    + add(collaborator)
    + remove(collaborator)
    + update(collaborator, name, email, address, phone, job, skills, birthDate, admissionDate, IDtype, taxpayerNumber, citizenNumber)
    + getCollaborators()
}

class Repositories {
    + getInstance()
    + getSkillRepository()
    + getCollaboratorRepository()
}

AddSkillToCollaboratorUI --> SkillController
AddSkillToCollaboratorUI --> CollaboratorController
SkillController --> Repositories
CollaboratorController --> Repositories
Repositories --> SkillRepository
Repositories --> CollaboratorRepository
CollaboratorRepository "1" --> "0..." Collaborator : Contains
SkillRepository "1" --> "0..." Skill : Contains

@enduml