@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "CollaboratorController" as CTRL
participant "skill\n:Skill" as SKILL

autonumber 16
-> CTRL: addSkills(Skills, collaborator)

autonumber 16.1
activate CTRL
    group add Skills to Collaborator

        loop for each skill in Skills
            CTRL -> Collaborator: addSkill(skill)
        end

        activate Collaborator
        alt if error
            Collaborator -> SKILL: return error
            SKILL -> CTRL: return error
            <-- CTRL : return error
        else if success
            Collaborator -> SKILL: return updated skill list
            SKILL -> CTRL: return updated skill list
            <-- CTRL : return the updated skill list
        end

        deactivate Collaborator
    deactivate SKILL
    end

    autonumber 17
deactivate CTRL


@enduml