x@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction


class Skill {
    - String name
    - String informalDescription
    - String technicalDescription


    + Skill(name, skillCategory, informalDescription, technicalDescription)
}

class SkillController {
    + SkillController(technicalSkillRepository, organizationRepository)
    + getSkills()
    + createSkill\(name,informalDescription, technicalDescription)
    + assignSkillToEmployee(skill, employee)
    - getEmployeeFromSession()
}



class AddSkillToACollaboratorUI {
}

class CollaboratorRepository{
    + getCollaborators()
}

class SkillRepository{
    + getSkills()
}
class Collaborators{
    -String name
    -String birthdate
    -String admission date
    -String address
    -Int contact
    -String identification document
    -String identification number
    -List<Skill> skills
}

class CollaboratorController{
    + getCollaboratorByEmail(collaborators)
}

AddSkillToACollaboratorUI --> SkillController
SkillController -> SkillRepository
AddSkillToACollaboratorUI -> CollaboratorController
CollaboratorController -> CollaboratorRepository
CollaboratorRepository "1" -> "0..." Collaborators : Contains
SkillRepository "1" -> "0..." Skill : Contains


@enduml