@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



'hide footbox
participant ":CollaboratorController" as CTRL
participant "CollaboratorRepository" as REP

autonumber 14
-> CTRL : getCollaboratorByEmail(email)
    group get collaborator by email
        CTRL -> REP: getCollaboratorList()
        activate REP
             REP -> CTRL: returns collaborator list
        deactivate REP

        CTRL -> CTRL: get the collaborator\nwith the desired email
    end
autonumber 14.1
activate CTRL


    autonumber 15
    alt if collaborator exists
        <--CTRL: return collaborator
    else collaborator does not exist
        <-- CTRL : return an error
    end
deactivate CTRL

@enduml