@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant ":JobController" as JC
participant "jobRepository:\nJobRepository" as jobRepository
participant ":JobController" as JC
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\nJobRepository" as jobRepository


autonumber 3
-> JC : get job list
autonumber 4
activate JC

    group Get Job List

        JC -> GlobRepo : getInstance()
            activate GlobRepo

            GlobRepo --> JC : repositories
            deactivate GlobRepo

            JC -> PLAT : getJobRepository()
            activate PLAT

            PLAT -->  JC: jobRepository
            deactivate PLAT

            JC -> jobRepository : getJobs()
            activate jobRepository

            jobRepository -> JC : jobsList
            deactivate jobRepository

    end
    autonumber 7
    <-- JC : job list
deactivate JC

@enduml