@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":JobController" as JC
participant ":CollaboratorController" as CTRL
participant ":Repositories" as GlobRepo
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant ":Collaborator" as CLB
participant "jobRepository:\nJobRepository" as jobRepository


activate HRM

        HRM -> UI : wants to register a new collaborator
        activate UI

        UI --> HRM : asks for the info needed (name, birthdate, contactMobile, email, address, \n city, documentType[], documentCode, admissionDate)
        deactivate UI

        HRM -> UI : types requested data
        activate UI

        UI -> JC: get job list





        activate JC

            JC -> GlobRepo : getInstance()
            activate GlobRepo

            GlobRepo --> JC : repositories
            deactivate GlobRepo

            JC -> PLAT : getJobRepository()
            activate PLAT

            PLAT -->  JC: jobRepository
            deactivate PLAT

            JC -> jobRepository : getJobs()
            activate jobRepository

            jobRepository -> JC : jobsList
            deactivate jobRepository


            JC --> UI : job list

        deactivate JC



        UI --> HRM : shows the list of jobs and requests to select one
        deactivate UI


        HRM -> UI : select the job
        activate UI

        UI --> HRM: shows all data and requests for confirmation
        deactivate UI

        HRM -> UI: confirms the data
        activate UI

        UI -> CTRL : create collaborator

        deactivate UI

        activate CTRL

            CTRL -> GlobRepo : getInstance()
            activate GlobRepo

            GlobRepo --> CTRL : repositories
            deactivate GlobRepo

            CTRL -> PLAT : getCollaboratorRepository()
            activate PLAT

            PLAT -->  CTRL: collaboratorRepository
            deactivate PLAT

            CTRL -> CLBREP : createCLB(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType, identificationNumber, admissionDate, job, taxpayerNumber)


            activate CLBREP
            CLBREP->CLB** : create(name, birthdate, contactMobile, email, address, zipCode,\n city, documentType, identificationNumber, admissionDate, job, taxpayerNumber)

            deactivate CLBREP


            activate CLB
                    CLB -> CLB : verifyCollaborator()

                    CLB -> CTRL : returnCollaborator()
                deactivate CLB

                CTRL -> CLBREP: addCollaborator(collaborator)

                activate CLBREP

                   CLBREP --> CTRL : success
                deactivate CLBREP

                CTRL --> UI : success
        deactivate CTRL

        activate UI
        UI --> HRM : shows success message (collaborator created successfully)
        deactivate UI


deactivate HRM


@enduml
