@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":CollaboratorController" as CTRL
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant ":Collaborator" as CLB
participant "jobRepository:\nJobRepository" as jobRepository


activate HRM

        HRM -> UI : wants to register a new collaborator
        activate UI

        UI --> HRM : asks for the info needed (name, birthdate, contactMobile, email, address, \n city, documentType[], documentCode, admissionDate)
        deactivate UI

        HRM -> UI : types requested data
        activate UI

        UI -> CTRL: get job List


        activate CTRL

            CTRL -> jobRepository : getJobs()
            activate jobRepository

            jobRepository -> CTRL : jobsList
            deactivate jobRepository


            CTRL --> UI : job List
        deactivate CTRL



        UI --> HRM : shows the list of jobs and requests to select one
        deactivate UI


        HRM -> UI : select the job
        activate UI

        UI --> HRM: shows all data and requests for confirmation
        deactivate UI

        HRM -> UI: confirms the data
        activate UI

        UI -> CTRL : create collaborator

        deactivate UI

        activate CTRL

            CTRL -> CLB** : createCLB(name, birthdate, contactMobile, email, address,\n city, documentType, identificationNumber, admissionDate, job, taxpayerNumber)

                activate CLB
                    CLB -> CLB : verifyCollaborator()

                    CLB -> CTRL : returnCollaborator()
                deactivate CLB

                CTRL -> CLBREP: addCollaborator(collaborator)

                activate CLBREP

                   CLBREP --> CTRL : success
                deactivate CLBREP

                CTRL --> UI : success
        deactivate CTRL

        activate UI
        UI --> HRM : shows success message (collaborator created successfully)
        deactivate UI


deactivate HRM


@enduml
