@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false



participant ":JobController" as JC
participant "jobRepository:\nJobRepository" as jobRepository


autonumber 3
-> JC : get job list
autonumber 4
activate JC

    group Get Job List
        JC -> jobRepository: getJobs()

        activate jobRepository

        jobRepository -> JC: jobsList
        deactivate jobRepository


    end
    autonumber 7
    <-- JC : job list
deactivate JC

@enduml