@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CollaboratorController" as CTRL
participant "collaboratorRepository:\nCollaboratorRepository" as CLBREP
participant ":Collaborator" as CLB
participant "jobRepository:\nJobRepository" as jobRepository

autonumber 12
-> CTRL : create collaborator
autonumber 13

activate CTRL
    group Register collaborator
        CTRL -> CLB** : createCLB(name, birthdate, contactMobile, email, address,\n city, documentType, identificationNumber, admissionDate, job, taxpayerNumber)

        activate CLB
            CLB -> CLB : verifyCollaborator()

            CLB -> CTRL : returnCollaborator()
        deactivate CLB

        CTRL -> CLBREP: addCollaborator(collaborator)

        activate CLBREP

            CLBREP -> CTRL : sucess
        deactivate CLBREP

    end group

    autonumber 18
    <-- CTRL : sucess

deactivate CTRL


@enduml