@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram

autonumber

actor "Green Space\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to add a new entry to the Agenda
    activate System


    System --> Employee : shows the available entries
    deactivate System

    Employee -> System : chooses the entry
    activate System

    System --> Employee : asks to confirm the data
    deactivate System

    Employee -> System : confirms the data
    activate System

    System --> Employee : shows the success of the operation
    deactivate System

@enduml
