@startuml

hide circle
hide methods

title Register a Skill

class registerSkill {
    technicalSkill
}

class TechnicalSkill{
    Name
    SmallDescription
    FullDescription
}

registerSkill -  TechnicalSkill : registers >

@enduml
