@startuml
!theme plain

hide methods
hide circle

class company{
         name
         vatNumber
         website
         phoneNumber
         email
}

class Collaborator {
     name
     birthdate
     admissionDate
     address
     contactInfo
     idDocType
     idDocNumber
}

class Team{
    collaborators
}

class HRM {
    name
    birthdate
    admissionDate
    address
    Taxpayer number
    contactInfo
    idDocType
    idDocNumber
}

class Task {
        reference
        description
        informalDesc
        technicalDesc
        duration
        cost
}

company "1" - "0...*" HRM : has >
company "1" -- "0...*" Collaborator : has >
HRM "1" - "*" Team : generates >
Team "1" - "1...*" Collaborator : composed by >
Team "1" - "0...*" Task : has >
HRM "1" - "0...*" Task : creates  >
@enduml