@startuml
!theme plain
title US05 -  As a HRM, I want to generate a team proposal automatically.

'left to right direction

hide methods
hide circle

class company{
    +String name
    +String address
    +String contactInfo
    -List<Job> jobs
    -List<Skill> skills
    -List<HRM> hrms
    -List<Collaborator> collaborators
}

class Collaborator {
    +String name
    +Date birthdate
    +Date admissionDate
    -String address
    -String contactInfo
    -String idDocType
    -String idDocNumber
    -List<Skill> skills
}



class HRM {
    +String name
    +Date birthdate
    +Date admissionDate
    +String address
    -Int Taxpayer number
    -String contactInfo
    -String idDocType
    -String idDocNumber
}

class assignTeam{
    +List<Skill> requiredSkill
    +Int minimumTeamSize
    +Int maximumTeamSize
}


company --> HRM : has


HRM --> assignTeam : can


HRM <--> company : choose a skill


assignTeam --> Collaborator : chooses collaborators\n with the required skills

Collaborator --> HRM : returns the\nchoosen collaborators

@enduml