@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US003

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System : requests to create a new collaborator, specifying their job and essential characteristics
    activate System

        System --> HRM : requests data (collaborator info, job, characteristics of the job)
    deactivate System

    HRM -> System : types requested data
    activate System

        System --> HRM : displays all data and requests confirmation
    deactivate System

    HRM -> System : confirms data
    activate System

        System --> HRM : shows operation success
    deactivate System

@enduml