@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Green Space Manager (GSM)" as GSM
participant ":System" as System
autonumber

title System Sequence Diagram - US012
activate GSM



@enduml