@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Green Space Manager \n(GSM)" as GSM
participant ":AddVehicleToAgendaEntryUI" as UI
participant ":AgendaController" as agendaController
participant ":VehicleController" as vehicleController
participant ":Repositories" as RepositorySingleton
participant "repositories:\nRepositories" as PLAT

activate GSM

GSM -> UI : requests to assign one or more vehicles to an entry
activate UI
UI --> GSM : requests to select the entry
deactivate UI
GSM -> UI : selects the entry
activate UI
    UI --> GSM : requests to select the vehicles the user wants to add
deactivate UI
    GSM -> UI : selects the vehicle(s)
   activate UI
       UI --> GSM : shows all data and requests confirmation
       deactivate UI
   deactivate UI
       GSM -> UI : confirms data
       activate UI
       UI --> GSM: notifies successful vehicle registration
   deactivate UI
Controller -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> Controller: repositories
                                        deactivate RepositorySingleton

                                        Controller -> PLAT : getGreenSpaceRepository()
                                        activate PLAT

                                            PLAT --> Controller : greenSpaceRepository
                                        deactivate PLAT

@enduml