@startuml
'https://plantuml.com/sequence-diagram

autonumber

HR -> Bob: Authentication Request
Bob --> HR: Authentication Response

HR -> Bob: Another authentication Request
HR <-- Bob: another authentication Response
@enduml