@startuml
!theme plain


actor "Human Resources\nManager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to generate a new team proposal
    activate System

        System --> Employee : requests maximum and minimum team size
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : Displays team skills for selection.
    deactivate System

    Employee -> System : selects the skills that the team needs to have

    activate System

        System --> Employee : shows the team proposal
    deactivate System

    Employee -> System : accepts or refuses the team proposal
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml